create table if not exists media
(
    id            int generated by default as identity primary key,
    filename      varchar(255) not null,
    hash          varchar(64)  not null,
    creation_date timestamp(0) not null,
    location varchar(255),
    latitude DECIMAL(15,10) default 0.0,
    longitude DECIMAL(15,10) default 0.0
);

CREATE INDEX if not exists media_dtid ON media (creation_date, id)