create table if not exists media
(
    id            int generated by default as identity primary key,
    filename      varchar(255) not null,
    hash          varchar(64)  not null,
    creation_date timestamp(0) not null,
    location varchar(255),
    latitude DECIMAL(15,10) default 0.0,
    longitude DECIMAL(15,10) default 0.0
);

CREATE INDEX if not exists media_dtid ON media (creation_date, id);

create table if not exists media_task
(
    id            int generated by default as identity primary key,
    filename      varchar(4096) not null,
    status        varchar(10) default 'PENDING' not null
);

CREATE INDEX if not exists media_task_status ON media_task(status);